swagger: '2.0'
host: "localhost:8080"
basePath: "/"
schemes:
  - http
info:
  title: 'GeohistoricalData API'
  description: 'A simple API to access the data and services of the project GeohistoricalData. Find out more at [http://geohistoricaldata.org/api/docs](http://geohistoricaldata.org/api/docs)'
  version: '1.0.0'
  termsOfService: ''
  contact:
    email: "contact@geohistoricaldata.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "geocoding"
    description: "Geocode a set of pairs <Address, Date>."
    externalDocs:
      description: "Find out more"
      url: "http://api.geohistoricaldata.org/docs"
paths:
  /geocoding:
    #Method POST is used for batch geocoding of multiples addresses
    post:
      tags:
      - "Geocoding"
      summary: "Geocode an adress at a given date."
      description: "Some description."
      operationId: "geocodePOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: "body"
        name: "body"
        schema:
          type: "array"
          items:
            $ref: "#/definitions/GeocodingQuery"
      responses:
        200:
          description: "Success"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
    #Method GET allows for a single geocoding request of an address
    get:
      tags:
      - "Geocoding"
      summary: "Geocode an adress at a given date."
      description: "Some description."
      operationId: "geocodeGET"
      parameters:
        - in: "query"
          name: "address"
          type: "string"
          default: "12 rue du temple"
        - in: "query"
          name: "date"
          type: "integer"
          default: 1850
        - in: "query"          
          name: precision
          type: "boolean"
          default: true
        - in: query
          name: "maxresults"
          type: "integer"
          default: 1
      responses:
        200:
          description: "Success"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Geocoding"

definitions:
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
        
  GeocodingSet:
      type: "array"
      xml:
        name: "queryset"
        wrapped: true
      minItems: 1        
      items:
        $ref: "#/definitions/GHObject"
        
  GeocodingQuery:
      type: "object"
      xml:
        name: "geocoding-query"
      required:
        - "address"
        - "date"
      properties:
        address:
          type: "string"
          example: "1 rue du Temple, Paris"
        date:
          type: "integer"
          example: 1850
        precision:
          type: "boolean"
          default: true
          example: true
          xml:
            name: "precise-geocoding"
        maxresults:
          type: "integer"
          default: 1
          example: 1
          xml:
            name: "max-results"
