swagger: '2.0'
host: "localhost:8080"
basePath: "/api"
schemes:
  - http
info:
  title: 'GeohistoricalData API'
  description: 'A simple API to access the data and services of the project GeohistoricalData. Find out more at [http://geohistoricaldata.org/api/docs](http://geohistoricaldata.org/api/docs)'
  version: '1.0.0'
  termsOfService: ''
  contact:
    email: "contact@geohistoricaldata.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "geocoding"
    description: "Geocode a set of pairs <Address, Date>."
    externalDocs:
      description: "Find out more"
      url: "http://geohistoricaldata.org/api/docs/geocoding"
paths:
  #GeocodingSet
  #CREATE
  /geocoding:
    post:
      tags:
      - "geocoding"
      summary: "Geocode an adress at a given date."
      description: "Some description."
      operationId: "geocode"
      consumes:
      - "application/json"
      #- "application/xml" #Temporarily disabled: objects encoded in XML  don't pass the validator...
      produces:
      - "application/json"
      #- "application/xml" #Temporarily disabled: objects encoded in XML  don't pass the validator...
      parameters: 
      - in: "body"
        name: "body"
        schema: 
          $ref: "#/definitions/GeocodingQuerySet"  
      responses:
        200:
          description: "Success"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
        
  GeocodingQuerySet:
      type: "array"
      xml:
        name: "queryset"
        wrapped: true
      minItems: 1        
      items:
        $ref: "#/definitions/GHObject"
        
  GHObject:
      type: "object"
      xml:
        name: "geohistorical-object"
      required:
        - "address"
        - "date"
      properties:
        address:
          type: "string"
          example: "1 rue du Temple, Paris"
        date:
          type: "integer"
          example: 1850
        precision:
          type: "boolean"
          default: true
          example: true
          xml:
            name: "precise-geocoding"
        maxresults:
          type: "integer"
          default: 1
          example: 1
          xml:
            name: "max-results"